language: python
python:
- "3.6"
install: pip install html5validator Jinja2 Markdown Pygments
script: |
  if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == master ]; then
    git fetch origin code:code
    git show code:Makefile > Makefile
    make ci-test HTMLROOT=.
  else
    make ci-test
  fi
