name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install html5validator Jinja2 Markdown Pygments
    - name: Test master
      if: endsWith(github.ref, '/master')
      run: |
        git fetch origin code:code
        git show code:Makefile > Makefile
        make ci-test HTMLROOT=.
    - name: Test code
      if: endsWith(github.ref, '/code')
      run: |
        make ci-test
